config/routes.rb
Rails.application.routes.draw do
  
  root 'jobs#index'
  resources :jobs

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  
  before_action :get_job, only: [:show,:update,:destroy,:edit]
  def index
    if params[:category].blank?
      @job = Job.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @job = Job.where(category_id:@category_id).order("created_at DESC") 
    end
  end
  
  def show
   
  end
   
  def new
    @job = Job.new
  end
  
  def create
    @job = Job.new(jobs_params)
    if @job.save
      redirect_to @job
    else
      render('new')
    end
  end
  
  def edit
    
  end
  
  def update
    if @job.update(jobs_params)
      redirect_to @job
    else
      render('edit')
    end
  end
  
  def destroy
    @job.destroy
    redirect_to root_path
  end
  
  
  private
    def jobs_params
     params.require(:job).permit(:job, :description, :company, :url,:category_id) 
    end
    
    def get_job
      @job = Job.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.haml
.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h2=@title
			.panel-body
				= simple_form_for(@job, html:{ class: 'form-horizontal'}) do |f|
					=f.collection_select :category_id, Category.all, :id, :name, {promt: "Choose Category"}, input_html:{class:"dropdown-toggle form-control"}
					=f.input :job, label: "Job Title", input_html:{class: "form-control"}
					=f.input :description, label: "Job Description", input_html:{class: "form-control"}
					=f.input :company, label: "Company", input_html:{class: "form-control"}
					=f.input :url, label: "Companies URL", input_html:{class: "form-control"}
					%br/
					=f.button :submit,class:"form-control btn btn-primary"
			=link_to "Back",:back,class:"btn btn-danger"




app/views/jobs/edit.html.haml
-@title = "Edit Job"

= render('form')

app/views/jobs/index.html.haml
#jobs
  - @job.each do |job|
    .job
      %h2= link_to job.job, job_path(job)
      %p= job.description
    
  

app/views/jobs/new.html.haml
-@title = "New Job"
=render('form')


app/views/jobs/show.html.haml

#jobs
  .job
    %h2= @job.job 
    %p= @job.description
    %p= @job.company
    %button.btn.btn-default= link_to "Apply for Job", @job.url

#links
  =link_to 'Back', root_path, class:"btn btn-sm btn-default" 
  =link_to 'Edit', edit_job_path(@job), class:"btn btn-sm btn-default" 
  =link_to 'Delete', @job, method: :delete, data: {confirm:"Are you sure?"}, class:"btn btn-sm btn-default" 

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Ruby on Rails Jobs
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true 
    = csrf_meta_tags 
%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand Rails Jobs
      %ul.nav.navbar-nav
        %li= link_to "Home", root_path
        - Category.all.each do |category|
          %li= link_to category.name, root_path(category: category.name)
      = link_to "New Job", new_job_path,class: "navbar-text navbar-right navbar-link"  
  .container
    = yield